language: node_js

node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci
  - npm install -g react-scripts


before_script:
  - npm start &
  - npm run client &

script:
  - npm run cypress:run
